import 'dart:io';

import 'irs.dart';

const generatedLibrary = 'package:sugar/time_zone_generated.g.dart';
const _output = 'lib/time_zone_generated.g.dart';
const _header = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
//
// **************************************************************************
// Generated by: sugar/tool/timezone/main.dart
// **************************************************************************
// 
// ignore_for_file: type=lint

/// Contains [Location]s mechanically generated from the IANA timezone database. This provides type-safe access to said
/// [Location]s.
///
/// See [Locations] for more information.
library sugar.time.zone.generated;

import 'package:sugar/time_zone.dart';

''';

extension LocationsLibrary on Never {

  static void generate(RootNamespaceIR namespace) {
    final buffer = StringBuffer(_header);
    _traverse(buffer, namespace.namespaces);
    File(_output).writeAsStringSync(buffer.toString());
  }

  static void _traverse(StringBuffer buffer, List<NestedNamespaceIR> namespaces) {
    for (final namespace in namespaces) {
      buffer.writeln("export '${namespace.toPackagePath()}';");
      _traverse(buffer, namespace.namespaces);
    }
  }

}
