// GENERATED CODE - DO NOT MODIFY BY HAND
//
// **************************************************************************
// Generated by: sugar/tool/timezone/main.dart
// **************************************************************************
// 
// ignore_for_file: type=lint

/// Contains [Location]s mechanically generated from the IANA timezone database. This provides type-safe access to said
/// [Location]s.
///
/// See [Locations] for more information.
library sugar.time.zone.generated;

import 'package:sugar/time_zone.dart';

export 'package:sugar/src/time/zone/locations/africa.g.dart';
export 'package:sugar/src/time/zone/locations/america.g.dart';
export 'package:sugar/src/time/zone/locations/argentina.g.dart';
export 'package:sugar/src/time/zone/locations/indiana.g.dart';
export 'package:sugar/src/time/zone/locations/kentucky.g.dart';
export 'package:sugar/src/time/zone/locations/north_dakota.g.dart';
export 'package:sugar/src/time/zone/locations/antarctica.g.dart';
export 'package:sugar/src/time/zone/locations/arctic.g.dart';
export 'package:sugar/src/time/zone/locations/asia.g.dart';
export 'package:sugar/src/time/zone/locations/atlantic.g.dart';
export 'package:sugar/src/time/zone/locations/australia.g.dart';
export 'package:sugar/src/time/zone/locations/brazil.g.dart';
export 'package:sugar/src/time/zone/locations/canada.g.dart';
export 'package:sugar/src/time/zone/locations/chile.g.dart';
export 'package:sugar/src/time/zone/locations/europe.g.dart';
export 'package:sugar/src/time/zone/locations/indian.g.dart';
export 'package:sugar/src/time/zone/locations/mexico.g.dart';
export 'package:sugar/src/time/zone/locations/pacific.g.dart';
export 'package:sugar/src/time/zone/locations/us.g.dart';
