// GENERATED CODE - DO NOT MODIFY BY HAND
//
// **************************************************************************
// Generated by: sugar/tool/timezone/main.dart
// **************************************************************************
// 
// ignore_for_file: type=lint

import 'package:sugar/src/time/zone/location.dart';
import 'package:sugar/src/time/offset.dart';
/// A namespace that contains [Location]s and nested namespaces in `Etc`.
/// 
/// See [Location]s for more information.
class Etc {

  const Etc();


  /// A [Location] that represents `Etc/GMT`.
  Location get gmt => Etc._gmt;

  /// A [Location] that represents `Etc/GMT+0`.
  Location get gmtPlus0 => Etc._gmtPlus0;

  /// A [Location] that represents `Etc/GMT+1`.
  Location get gmtPlus1 => Etc._gmtPlus1;

  /// A [Location] that represents `Etc/GMT+10`.
  Location get gmtPlus10 => Etc._gmtPlus10;

  /// A [Location] that represents `Etc/GMT+11`.
  Location get gmtPlus11 => Etc._gmtPlus11;

  /// A [Location] that represents `Etc/GMT+12`.
  Location get gmtPlus12 => Etc._gmtPlus12;

  /// A [Location] that represents `Etc/GMT+2`.
  Location get gmtPlus2 => Etc._gmtPlus2;

  /// A [Location] that represents `Etc/GMT+3`.
  Location get gmtPlus3 => Etc._gmtPlus3;

  /// A [Location] that represents `Etc/GMT+4`.
  Location get gmtPlus4 => Etc._gmtPlus4;

  /// A [Location] that represents `Etc/GMT+5`.
  Location get gmtPlus5 => Etc._gmtPlus5;

  /// A [Location] that represents `Etc/GMT+6`.
  Location get gmtPlus6 => Etc._gmtPlus6;

  /// A [Location] that represents `Etc/GMT+7`.
  Location get gmtPlus7 => Etc._gmtPlus7;

  /// A [Location] that represents `Etc/GMT+8`.
  Location get gmtPlus8 => Etc._gmtPlus8;

  /// A [Location] that represents `Etc/GMT+9`.
  Location get gmtPlus9 => Etc._gmtPlus9;

  /// A [Location] that represents `Etc/GMT-0`.
  Location get gmtMinus0 => Etc._gmtMinus0;

  /// A [Location] that represents `Etc/GMT-1`.
  Location get gmtMinus1 => Etc._gmtMinus1;

  /// A [Location] that represents `Etc/GMT-10`.
  Location get gmtMinus10 => Etc._gmtMinus10;

  /// A [Location] that represents `Etc/GMT-11`.
  Location get gmtMinus11 => Etc._gmtMinus11;

  /// A [Location] that represents `Etc/GMT-12`.
  Location get gmtMinus12 => Etc._gmtMinus12;

  /// A [Location] that represents `Etc/GMT-13`.
  Location get gmtMinus13 => Etc._gmtMinus13;

  /// A [Location] that represents `Etc/GMT-14`.
  Location get gmtMinus14 => Etc._gmtMinus14;

  /// A [Location] that represents `Etc/GMT-2`.
  Location get gmtMinus2 => Etc._gmtMinus2;

  /// A [Location] that represents `Etc/GMT-3`.
  Location get gmtMinus3 => Etc._gmtMinus3;

  /// A [Location] that represents `Etc/GMT-4`.
  Location get gmtMinus4 => Etc._gmtMinus4;

  /// A [Location] that represents `Etc/GMT-5`.
  Location get gmtMinus5 => Etc._gmtMinus5;

  /// A [Location] that represents `Etc/GMT-6`.
  Location get gmtMinus6 => Etc._gmtMinus6;

  /// A [Location] that represents `Etc/GMT-7`.
  Location get gmtMinus7 => Etc._gmtMinus7;

  /// A [Location] that represents `Etc/GMT-8`.
  Location get gmtMinus8 => Etc._gmtMinus8;

  /// A [Location] that represents `Etc/GMT-9`.
  Location get gmtMinus9 => Etc._gmtMinus9;

  /// A [Location] that represents `Etc/GMT0`.
  Location get gmt0 => Etc._gmt0;

  /// A [Location] that represents `Etc/Greenwich`.
  Location get greenwich => Etc._greenwich;

  /// A [Location] that represents `Etc/UCT`.
  Location get uct => Etc._uct;

  /// A [Location] that represents `Etc/UTC`.
  Location get utc => Etc._utc;

  /// A [Location] that represents `Etc/Universal`.
  Location get universal => Etc._universal;

  /// A [Location] that represents `Etc/Zulu`.
  Location get zulu => Etc._zulu;


  static final Location _gmt = Location(
    'Etc/GMT',
    [],
    const [
    ],
  );

  static final Location _gmtPlus0 = Location(
    'Etc/GMT+0',
    [],
    const [
    ],
  );

  static final Location _gmtPlus1 = Location(
    'Etc/GMT+1',
    [],
    const [
    ],
  );

  static final Location _gmtPlus10 = Location(
    'Etc/GMT+10',
    [],
    const [
    ],
  );

  static final Location _gmtPlus11 = Location(
    'Etc/GMT+11',
    [],
    const [
    ],
  );

  static final Location _gmtPlus12 = Location(
    'Etc/GMT+12',
    [],
    const [
    ],
  );

  static final Location _gmtPlus2 = Location(
    'Etc/GMT+2',
    [],
    const [
    ],
  );

  static final Location _gmtPlus3 = Location(
    'Etc/GMT+3',
    [],
    const [
    ],
  );

  static final Location _gmtPlus4 = Location(
    'Etc/GMT+4',
    [],
    const [
    ],
  );

  static final Location _gmtPlus5 = Location(
    'Etc/GMT+5',
    [],
    const [
    ],
  );

  static final Location _gmtPlus6 = Location(
    'Etc/GMT+6',
    [],
    const [
    ],
  );

  static final Location _gmtPlus7 = Location(
    'Etc/GMT+7',
    [],
    const [
    ],
  );

  static final Location _gmtPlus8 = Location(
    'Etc/GMT+8',
    [],
    const [
    ],
  );

  static final Location _gmtPlus9 = Location(
    'Etc/GMT+9',
    [],
    const [
    ],
  );

  static final Location _gmtMinus0 = Location(
    'Etc/GMT-0',
    [],
    const [
    ],
  );

  static final Location _gmtMinus1 = Location(
    'Etc/GMT-1',
    [],
    const [
    ],
  );

  static final Location _gmtMinus10 = Location(
    'Etc/GMT-10',
    [],
    const [
    ],
  );

  static final Location _gmtMinus11 = Location(
    'Etc/GMT-11',
    [],
    const [
    ],
  );

  static final Location _gmtMinus12 = Location(
    'Etc/GMT-12',
    [],
    const [
    ],
  );

  static final Location _gmtMinus13 = Location(
    'Etc/GMT-13',
    [],
    const [
    ],
  );

  static final Location _gmtMinus14 = Location(
    'Etc/GMT-14',
    [],
    const [
    ],
  );

  static final Location _gmtMinus2 = Location(
    'Etc/GMT-2',
    [],
    const [
    ],
  );

  static final Location _gmtMinus3 = Location(
    'Etc/GMT-3',
    [],
    const [
    ],
  );

  static final Location _gmtMinus4 = Location(
    'Etc/GMT-4',
    [],
    const [
    ],
  );

  static final Location _gmtMinus5 = Location(
    'Etc/GMT-5',
    [],
    const [
    ],
  );

  static final Location _gmtMinus6 = Location(
    'Etc/GMT-6',
    [],
    const [
    ],
  );

  static final Location _gmtMinus7 = Location(
    'Etc/GMT-7',
    [],
    const [
    ],
  );

  static final Location _gmtMinus8 = Location(
    'Etc/GMT-8',
    [],
    const [
    ],
  );

  static final Location _gmtMinus9 = Location(
    'Etc/GMT-9',
    [],
    const [
    ],
  );

  static final Location _gmt0 = Location(
    'Etc/GMT0',
    [],
    const [
    ],
  );

  static final Location _greenwich = Location(
    'Etc/Greenwich',
    [],
    const [
    ],
  );

  static final Location _uct = Location(
    'Etc/UCT',
    [],
    const [
    ],
  );

  static final Location _utc = Location(
    'Etc/UTC',
    [],
    const [
    ],
  );

  static final Location _universal = Location(
    'Etc/Universal',
    [],
    const [
    ],
  );

  static final Location _zulu = Location(
    'Etc/Zulu',
    [],
    const [
    ],
  );


}


