// GENERATED CODE - DO NOT MODIFY BY HAND
//
// **************************************************************************
// Generated by: sugar/tool/timezone/main.dart
// **************************************************************************
// 
// ignore_for_file: type=lint

import 'package:sugar/src/time/zone/location.dart';
import 'package:sugar/src/time/offset.dart';
/// A namespace that contains [Location]s and nested namespaces in `Indian`.
/// 
/// See [Location]s for more information.
class Indian {

  const Indian();


  /// A [Location] that represents `Indian/Antananarivo`.
  Location get antananarivo => Indian._antananarivo;

  /// A [Location] that represents `Indian/Chagos`.
  Location get chagos => Indian._chagos;

  /// A [Location] that represents `Indian/Christmas`.
  Location get christmas => Indian._christmas;

  /// A [Location] that represents `Indian/Cocos`.
  Location get cocos => Indian._cocos;

  /// A [Location] that represents `Indian/Comoro`.
  Location get comoro => Indian._comoro;

  /// A [Location] that represents `Indian/Kerguelen`.
  Location get kerguelen => Indian._kerguelen;

  /// A [Location] that represents `Indian/Mahe`.
  Location get mahe => Indian._mahe;

  /// A [Location] that represents `Indian/Maldives`.
  Location get maldives => Indian._maldives;

  /// A [Location] that represents `Indian/Mauritius`.
  Location get mauritius => Indian._mauritius;

  /// A [Location] that represents `Indian/Mayotte`.
  Location get mayotte => Indian._mayotte;

  /// A [Location] that represents `Indian/Reunion`.
  Location get reunion => Indian._reunion;


  static final Location _antananarivo = Location(
    'Indian/Antananarivo',
    [-1946168836, -1309746600, -1261969200, -1041388200, -865305900],
    const [
      Timezone(RawOffset('+02:30', 9000), abbreviation: '+0230', dst: false),
      Timezone(RawOffset('+03:00', 10800), abbreviation: 'EAT', dst: false),
      Timezone(RawOffset('+02:30', 9000), abbreviation: '+0230', dst: false),
      Timezone(RawOffset('+02:45', 9900), abbreviation: '+0245', dst: false),
      Timezone(RawOffset('+03:00', 10800), abbreviation: 'EAT', dst: false),
    ],
  );

  static final Location _chagos = Location(
    'Indian/Chagos',
    [-1988167780, 820436400],
    const [
      Timezone(RawOffset('+05:00', 18000), abbreviation: '+05', dst: false),
      Timezone(RawOffset('+06:00', 21600), abbreviation: '+06', dst: false),
    ],
  );

  static final Location _christmas = Location(
    'Indian/Christmas',
    [-2840164924, -1570084924],
    const [
      Timezone(RawOffset('+06:42:04', 24124), abbreviation: 'BMT', dst: false),
      Timezone(RawOffset('+07:00', 25200), abbreviation: '+07', dst: false),
    ],
  );

  static final Location _cocos = Location(
    'Indian/Cocos',
    [-2840163887, -1577946287, -873268200, -778410000],
    const [
      Timezone(RawOffset('+06:24:47', 23087), abbreviation: 'RMT', dst: false),
      Timezone(RawOffset('+06:30', 23400), abbreviation: '+0630', dst: false),
      Timezone(RawOffset('+09:00', 32400), abbreviation: '+09', dst: false),
      Timezone(RawOffset('+06:30', 23400), abbreviation: '+0630', dst: false),
    ],
  );

  static final Location _comoro = Location(
    'Indian/Comoro',
    [-1946168836, -1309746600, -1261969200, -1041388200, -865305900],
    const [
      Timezone(RawOffset('+02:30', 9000), abbreviation: '+0230', dst: false),
      Timezone(RawOffset('+03:00', 10800), abbreviation: 'EAT', dst: false),
      Timezone(RawOffset('+02:30', 9000), abbreviation: '+0230', dst: false),
      Timezone(RawOffset('+02:45', 9900), abbreviation: '+0245', dst: false),
      Timezone(RawOffset('+03:00', 10800), abbreviation: 'EAT', dst: false),
    ],
  );

  static final Location _kerguelen = Location(
    'Indian/Kerguelen',
    [-2840158440, -315636840],
    const [
      Timezone(RawOffset('+04:54', 17640), abbreviation: 'MMT', dst: false),
      Timezone(RawOffset('+05:00', 18000), abbreviation: '+05', dst: false),
    ],
  );

  static final Location _mahe = Location(
    'Indian/Mahe',
    [-1577936472],
    const [
      Timezone(RawOffset('+04:00', 14400), abbreviation: '+04', dst: false),
    ],
  );

  static final Location _maldives = Location(
    'Indian/Maldives',
    [-2840158440, -315636840],
    const [
      Timezone(RawOffset('+04:54', 17640), abbreviation: 'MMT', dst: false),
      Timezone(RawOffset('+05:00', 18000), abbreviation: '+05', dst: false),
    ],
  );

  static final Location _mauritius = Location(
    'Indian/Mauritius',
    [-1988164200, 403041600, 417034800, 1224972000, 1238274000],
    const [
      Timezone(RawOffset('+04:00', 14400), abbreviation: '+04', dst: false),
      Timezone(RawOffset('+05:00', 18000), abbreviation: '+05', dst: true),
      Timezone(RawOffset('+04:00', 14400), abbreviation: '+04', dst: false),
      Timezone(RawOffset('+05:00', 18000), abbreviation: '+05', dst: true),
      Timezone(RawOffset('+04:00', 14400), abbreviation: '+04', dst: false),
    ],
  );

  static final Location _mayotte = Location(
    'Indian/Mayotte',
    [-1946168836, -1309746600, -1261969200, -1041388200, -865305900],
    const [
      Timezone(RawOffset('+02:30', 9000), abbreviation: '+0230', dst: false),
      Timezone(RawOffset('+03:00', 10800), abbreviation: 'EAT', dst: false),
      Timezone(RawOffset('+02:30', 9000), abbreviation: '+0230', dst: false),
      Timezone(RawOffset('+02:45', 9900), abbreviation: '+0245', dst: false),
      Timezone(RawOffset('+03:00', 10800), abbreviation: 'EAT', dst: false),
    ],
  );

  static final Location _reunion = Location(
    'Indian/Reunion',
    [-1577936472],
    const [
      Timezone(RawOffset('+04:00', 14400), abbreviation: '+04', dst: false),
    ],
  );


}


