// GENERATED CODE - DO NOT MODIFY BY HAND
//
// **************************************************************************
// Generated by: sugar/tool/timezone/main.dart
// **************************************************************************
// 
// ignore_for_file: type=lint

import 'package:meta/meta.dart';

import 'package:sugar/src/time/zone/timezone.dart';

import 'package:sugar/src/time/zone/info/root.g.dart';
import 'package:sugar/src/time/zone/info/africa.g.dart';
import 'package:sugar/src/time/zone/info/america.g.dart';
import 'package:sugar/src/time/zone/info/argentina.g.dart';
import 'package:sugar/src/time/zone/info/indiana.g.dart';
import 'package:sugar/src/time/zone/info/kentucky.g.dart';
import 'package:sugar/src/time/zone/info/north_dakota.g.dart';
import 'package:sugar/src/time/zone/info/antarctica.g.dart';
import 'package:sugar/src/time/zone/info/arctic.g.dart';
import 'package:sugar/src/time/zone/info/asia.g.dart';
import 'package:sugar/src/time/zone/info/atlantic.g.dart';
import 'package:sugar/src/time/zone/info/australia.g.dart';
import 'package:sugar/src/time/zone/info/brazil.g.dart';
import 'package:sugar/src/time/zone/info/canada.g.dart';
import 'package:sugar/src/time/zone/info/chile.g.dart';
import 'package:sugar/src/time/zone/info/etc.g.dart';
import 'package:sugar/src/time/zone/info/europe.g.dart';
import 'package:sugar/src/time/zone/info/indian.g.dart';
import 'package:sugar/src/time/zone/info/mexico.g.dart';
import 'package:sugar/src/time/zone/info/pacific.g.dart';
import 'package:sugar/src/time/zone/info/us.g.dart';

/// The supported IANA TZ database timezones.
@internal const Set<String> iana = {
  'CET',
  'CST6CDT',
  'Cuba',
  'EET',
  'EST',
  'EST5EDT',
  'Egypt',
  'Eire',
  'Factory',
  'GB',
  'GB-Eire',
  'GMT',
  'GMT+0',
  'GMT-0',
  'GMT0',
  'Greenwich',
  'HST',
  'Hongkong',
  'Iceland',
  'Iran',
  'Israel',
  'Jamaica',
  'Japan',
  'Kwajalein',
  'Libya',
  'MET',
  'MST',
  'MST7MDT',
  'NZ',
  'NZ-CHAT',
  'Navajo',
  'PRC',
  'PST8PDT',
  'Poland',
  'Portugal',
  'ROC',
  'ROK',
  'Singapore',
  'Turkey',
  'UCT',
  'UTC',
  'Universal',
  'W-SU',
  'WET',
  'Zulu',
  'Africa/Abidjan',
  'Africa/Accra',
  'Africa/Addis_Ababa',
  'Africa/Algiers',
  'Africa/Asmara',
  'Africa/Asmera',
  'Africa/Bamako',
  'Africa/Bangui',
  'Africa/Banjul',
  'Africa/Bissau',
  'Africa/Blantyre',
  'Africa/Brazzaville',
  'Africa/Bujumbura',
  'Africa/Cairo',
  'Africa/Casablanca',
  'Africa/Ceuta',
  'Africa/Conakry',
  'Africa/Dakar',
  'Africa/Dar_es_Salaam',
  'Africa/Djibouti',
  'Africa/Douala',
  'Africa/El_Aaiun',
  'Africa/Freetown',
  'Africa/Gaborone',
  'Africa/Harare',
  'Africa/Johannesburg',
  'Africa/Juba',
  'Africa/Kampala',
  'Africa/Khartoum',
  'Africa/Kigali',
  'Africa/Kinshasa',
  'Africa/Lagos',
  'Africa/Libreville',
  'Africa/Lome',
  'Africa/Luanda',
  'Africa/Lubumbashi',
  'Africa/Lusaka',
  'Africa/Malabo',
  'Africa/Maputo',
  'Africa/Maseru',
  'Africa/Mbabane',
  'Africa/Mogadishu',
  'Africa/Monrovia',
  'Africa/Nairobi',
  'Africa/Ndjamena',
  'Africa/Niamey',
  'Africa/Nouakchott',
  'Africa/Ouagadougou',
  'Africa/Porto-Novo',
  'Africa/Sao_Tome',
  'Africa/Timbuktu',
  'Africa/Tripoli',
  'Africa/Tunis',
  'Africa/Windhoek',
  'America/Adak',
  'America/Anchorage',
  'America/Anguilla',
  'America/Antigua',
  'America/Araguaina',
  'America/Aruba',
  'America/Asuncion',
  'America/Atikokan',
  'America/Atka',
  'America/Bahia',
  'America/Bahia_Banderas',
  'America/Barbados',
  'America/Belem',
  'America/Belize',
  'America/Blanc-Sablon',
  'America/Boa_Vista',
  'America/Bogota',
  'America/Boise',
  'America/Buenos_Aires',
  'America/Cambridge_Bay',
  'America/Campo_Grande',
  'America/Cancun',
  'America/Caracas',
  'America/Catamarca',
  'America/Cayenne',
  'America/Cayman',
  'America/Chicago',
  'America/Chihuahua',
  'America/Ciudad_Juarez',
  'America/Coral_Harbour',
  'America/Cordoba',
  'America/Costa_Rica',
  'America/Creston',
  'America/Cuiaba',
  'America/Curacao',
  'America/Danmarkshavn',
  'America/Dawson',
  'America/Dawson_Creek',
  'America/Denver',
  'America/Detroit',
  'America/Dominica',
  'America/Edmonton',
  'America/Eirunepe',
  'America/El_Salvador',
  'America/Ensenada',
  'America/Fort_Nelson',
  'America/Fort_Wayne',
  'America/Fortaleza',
  'America/Glace_Bay',
  'America/Godthab',
  'America/Goose_Bay',
  'America/Grand_Turk',
  'America/Grenada',
  'America/Guadeloupe',
  'America/Guatemala',
  'America/Guayaquil',
  'America/Guyana',
  'America/Halifax',
  'America/Havana',
  'America/Hermosillo',
  'America/Indianapolis',
  'America/Inuvik',
  'America/Iqaluit',
  'America/Jamaica',
  'America/Jujuy',
  'America/Juneau',
  'America/Knox_IN',
  'America/Kralendijk',
  'America/La_Paz',
  'America/Lima',
  'America/Los_Angeles',
  'America/Louisville',
  'America/Lower_Princes',
  'America/Maceio',
  'America/Managua',
  'America/Manaus',
  'America/Marigot',
  'America/Martinique',
  'America/Matamoros',
  'America/Mazatlan',
  'America/Mendoza',
  'America/Menominee',
  'America/Merida',
  'America/Metlakatla',
  'America/Mexico_City',
  'America/Miquelon',
  'America/Moncton',
  'America/Monterrey',
  'America/Montevideo',
  'America/Montreal',
  'America/Montserrat',
  'America/Nassau',
  'America/New_York',
  'America/Nipigon',
  'America/Nome',
  'America/Noronha',
  'America/Nuuk',
  'America/Ojinaga',
  'America/Panama',
  'America/Pangnirtung',
  'America/Paramaribo',
  'America/Phoenix',
  'America/Port-au-Prince',
  'America/Port_of_Spain',
  'America/Porto_Acre',
  'America/Porto_Velho',
  'America/Puerto_Rico',
  'America/Punta_Arenas',
  'America/Rainy_River',
  'America/Rankin_Inlet',
  'America/Recife',
  'America/Regina',
  'America/Resolute',
  'America/Rio_Branco',
  'America/Rosario',
  'America/Santa_Isabel',
  'America/Santarem',
  'America/Santiago',
  'America/Santo_Domingo',
  'America/Sao_Paulo',
  'America/Scoresbysund',
  'America/Shiprock',
  'America/Sitka',
  'America/St_Barthelemy',
  'America/St_Johns',
  'America/St_Kitts',
  'America/St_Lucia',
  'America/St_Thomas',
  'America/St_Vincent',
  'America/Swift_Current',
  'America/Tegucigalpa',
  'America/Thule',
  'America/Thunder_Bay',
  'America/Tijuana',
  'America/Toronto',
  'America/Tortola',
  'America/Vancouver',
  'America/Virgin',
  'America/Whitehorse',
  'America/Winnipeg',
  'America/Yakutat',
  'America/Yellowknife',
  'America/Argentina/Buenos_Aires',
  'America/Argentina/Catamarca',
  'America/Argentina/ComodRivadavia',
  'America/Argentina/Cordoba',
  'America/Argentina/Jujuy',
  'America/Argentina/La_Rioja',
  'America/Argentina/Mendoza',
  'America/Argentina/Rio_Gallegos',
  'America/Argentina/Salta',
  'America/Argentina/San_Juan',
  'America/Argentina/San_Luis',
  'America/Argentina/Tucuman',
  'America/Argentina/Ushuaia',
  'America/Indiana/Indianapolis',
  'America/Indiana/Knox',
  'America/Indiana/Marengo',
  'America/Indiana/Petersburg',
  'America/Indiana/Tell_City',
  'America/Indiana/Vevay',
  'America/Indiana/Vincennes',
  'America/Indiana/Winamac',
  'America/Kentucky/Louisville',
  'America/Kentucky/Monticello',
  'America/North_Dakota/Beulah',
  'America/North_Dakota/Center',
  'America/North_Dakota/New_Salem',
  'Antarctica/Casey',
  'Antarctica/Davis',
  'Antarctica/DumontDUrville',
  'Antarctica/Macquarie',
  'Antarctica/Mawson',
  'Antarctica/McMurdo',
  'Antarctica/Palmer',
  'Antarctica/Rothera',
  'Antarctica/South_Pole',
  'Antarctica/Syowa',
  'Antarctica/Troll',
  'Antarctica/Vostok',
  'Arctic/Longyearbyen',
  'Asia/Aden',
  'Asia/Almaty',
  'Asia/Amman',
  'Asia/Anadyr',
  'Asia/Aqtau',
  'Asia/Aqtobe',
  'Asia/Ashgabat',
  'Asia/Ashkhabad',
  'Asia/Atyrau',
  'Asia/Baghdad',
  'Asia/Bahrain',
  'Asia/Baku',
  'Asia/Bangkok',
  'Asia/Barnaul',
  'Asia/Beirut',
  'Asia/Bishkek',
  'Asia/Brunei',
  'Asia/Calcutta',
  'Asia/Chita',
  'Asia/Choibalsan',
  'Asia/Chongqing',
  'Asia/Chungking',
  'Asia/Colombo',
  'Asia/Dacca',
  'Asia/Damascus',
  'Asia/Dhaka',
  'Asia/Dili',
  'Asia/Dubai',
  'Asia/Dushanbe',
  'Asia/Famagusta',
  'Asia/Gaza',
  'Asia/Harbin',
  'Asia/Hebron',
  'Asia/Ho_Chi_Minh',
  'Asia/Hong_Kong',
  'Asia/Hovd',
  'Asia/Irkutsk',
  'Asia/Istanbul',
  'Asia/Jakarta',
  'Asia/Jayapura',
  'Asia/Jerusalem',
  'Asia/Kabul',
  'Asia/Kamchatka',
  'Asia/Karachi',
  'Asia/Kashgar',
  'Asia/Kathmandu',
  'Asia/Katmandu',
  'Asia/Khandyga',
  'Asia/Kolkata',
  'Asia/Krasnoyarsk',
  'Asia/Kuala_Lumpur',
  'Asia/Kuching',
  'Asia/Kuwait',
  'Asia/Macao',
  'Asia/Macau',
  'Asia/Magadan',
  'Asia/Makassar',
  'Asia/Manila',
  'Asia/Muscat',
  'Asia/Nicosia',
  'Asia/Novokuznetsk',
  'Asia/Novosibirsk',
  'Asia/Omsk',
  'Asia/Oral',
  'Asia/Phnom_Penh',
  'Asia/Pontianak',
  'Asia/Pyongyang',
  'Asia/Qatar',
  'Asia/Qostanay',
  'Asia/Qyzylorda',
  'Asia/Rangoon',
  'Asia/Riyadh',
  'Asia/Saigon',
  'Asia/Sakhalin',
  'Asia/Samarkand',
  'Asia/Seoul',
  'Asia/Shanghai',
  'Asia/Singapore',
  'Asia/Srednekolymsk',
  'Asia/Taipei',
  'Asia/Tashkent',
  'Asia/Tbilisi',
  'Asia/Tehran',
  'Asia/Tel_Aviv',
  'Asia/Thimbu',
  'Asia/Thimphu',
  'Asia/Tokyo',
  'Asia/Tomsk',
  'Asia/Ujung_Pandang',
  'Asia/Ulaanbaatar',
  'Asia/Ulan_Bator',
  'Asia/Urumqi',
  'Asia/Ust-Nera',
  'Asia/Vientiane',
  'Asia/Vladivostok',
  'Asia/Yakutsk',
  'Asia/Yangon',
  'Asia/Yekaterinburg',
  'Asia/Yerevan',
  'Atlantic/Azores',
  'Atlantic/Bermuda',
  'Atlantic/Canary',
  'Atlantic/Cape_Verde',
  'Atlantic/Faeroe',
  'Atlantic/Faroe',
  'Atlantic/Jan_Mayen',
  'Atlantic/Madeira',
  'Atlantic/Reykjavik',
  'Atlantic/South_Georgia',
  'Atlantic/St_Helena',
  'Atlantic/Stanley',
  'Australia/ACT',
  'Australia/Adelaide',
  'Australia/Brisbane',
  'Australia/Broken_Hill',
  'Australia/Canberra',
  'Australia/Currie',
  'Australia/Darwin',
  'Australia/Eucla',
  'Australia/Hobart',
  'Australia/LHI',
  'Australia/Lindeman',
  'Australia/Lord_Howe',
  'Australia/Melbourne',
  'Australia/NSW',
  'Australia/North',
  'Australia/Perth',
  'Australia/Queensland',
  'Australia/South',
  'Australia/Sydney',
  'Australia/Tasmania',
  'Australia/Victoria',
  'Australia/West',
  'Australia/Yancowinna',
  'Brazil/Acre',
  'Brazil/DeNoronha',
  'Brazil/East',
  'Brazil/West',
  'Canada/Atlantic',
  'Canada/Central',
  'Canada/Eastern',
  'Canada/Mountain',
  'Canada/Newfoundland',
  'Canada/Pacific',
  'Canada/Saskatchewan',
  'Canada/Yukon',
  'Chile/Continental',
  'Chile/EasterIsland',
  'Etc/GMT',
  'Etc/GMT+0',
  'Etc/GMT+1',
  'Etc/GMT+10',
  'Etc/GMT+11',
  'Etc/GMT+12',
  'Etc/GMT+2',
  'Etc/GMT+3',
  'Etc/GMT+4',
  'Etc/GMT+5',
  'Etc/GMT+6',
  'Etc/GMT+7',
  'Etc/GMT+8',
  'Etc/GMT+9',
  'Etc/GMT-0',
  'Etc/GMT-1',
  'Etc/GMT-10',
  'Etc/GMT-11',
  'Etc/GMT-12',
  'Etc/GMT-13',
  'Etc/GMT-14',
  'Etc/GMT-2',
  'Etc/GMT-3',
  'Etc/GMT-4',
  'Etc/GMT-5',
  'Etc/GMT-6',
  'Etc/GMT-7',
  'Etc/GMT-8',
  'Etc/GMT-9',
  'Etc/GMT0',
  'Etc/Greenwich',
  'Etc/UCT',
  'Etc/UTC',
  'Etc/Universal',
  'Etc/Zulu',
  'Europe/Amsterdam',
  'Europe/Andorra',
  'Europe/Astrakhan',
  'Europe/Athens',
  'Europe/Belfast',
  'Europe/Belgrade',
  'Europe/Berlin',
  'Europe/Bratislava',
  'Europe/Brussels',
  'Europe/Bucharest',
  'Europe/Budapest',
  'Europe/Busingen',
  'Europe/Chisinau',
  'Europe/Copenhagen',
  'Europe/Dublin',
  'Europe/Gibraltar',
  'Europe/Guernsey',
  'Europe/Helsinki',
  'Europe/Isle_of_Man',
  'Europe/Istanbul',
  'Europe/Jersey',
  'Europe/Kaliningrad',
  'Europe/Kiev',
  'Europe/Kirov',
  'Europe/Kyiv',
  'Europe/Lisbon',
  'Europe/Ljubljana',
  'Europe/London',
  'Europe/Luxembourg',
  'Europe/Madrid',
  'Europe/Malta',
  'Europe/Mariehamn',
  'Europe/Minsk',
  'Europe/Monaco',
  'Europe/Moscow',
  'Europe/Nicosia',
  'Europe/Oslo',
  'Europe/Paris',
  'Europe/Podgorica',
  'Europe/Prague',
  'Europe/Riga',
  'Europe/Rome',
  'Europe/Samara',
  'Europe/San_Marino',
  'Europe/Sarajevo',
  'Europe/Saratov',
  'Europe/Simferopol',
  'Europe/Skopje',
  'Europe/Sofia',
  'Europe/Stockholm',
  'Europe/Tallinn',
  'Europe/Tirane',
  'Europe/Tiraspol',
  'Europe/Ulyanovsk',
  'Europe/Uzhgorod',
  'Europe/Vaduz',
  'Europe/Vatican',
  'Europe/Vienna',
  'Europe/Vilnius',
  'Europe/Volgograd',
  'Europe/Warsaw',
  'Europe/Zagreb',
  'Europe/Zaporozhye',
  'Europe/Zurich',
  'Indian/Antananarivo',
  'Indian/Chagos',
  'Indian/Christmas',
  'Indian/Cocos',
  'Indian/Comoro',
  'Indian/Kerguelen',
  'Indian/Mahe',
  'Indian/Maldives',
  'Indian/Mauritius',
  'Indian/Mayotte',
  'Indian/Reunion',
  'Mexico/BajaNorte',
  'Mexico/BajaSur',
  'Mexico/General',
  'Pacific/Apia',
  'Pacific/Auckland',
  'Pacific/Bougainville',
  'Pacific/Chatham',
  'Pacific/Chuuk',
  'Pacific/Easter',
  'Pacific/Efate',
  'Pacific/Enderbury',
  'Pacific/Fakaofo',
  'Pacific/Fiji',
  'Pacific/Funafuti',
  'Pacific/Galapagos',
  'Pacific/Gambier',
  'Pacific/Guadalcanal',
  'Pacific/Guam',
  'Pacific/Honolulu',
  'Pacific/Johnston',
  'Pacific/Kanton',
  'Pacific/Kiritimati',
  'Pacific/Kosrae',
  'Pacific/Kwajalein',
  'Pacific/Majuro',
  'Pacific/Marquesas',
  'Pacific/Midway',
  'Pacific/Nauru',
  'Pacific/Niue',
  'Pacific/Norfolk',
  'Pacific/Noumea',
  'Pacific/Pago_Pago',
  'Pacific/Palau',
  'Pacific/Pitcairn',
  'Pacific/Pohnpei',
  'Pacific/Ponape',
  'Pacific/Port_Moresby',
  'Pacific/Rarotonga',
  'Pacific/Saipan',
  'Pacific/Samoa',
  'Pacific/Tahiti',
  'Pacific/Tarawa',
  'Pacific/Tongatapu',
  'Pacific/Truk',
  'Pacific/Wake',
  'Pacific/Wallis',
  'Pacific/Yap',
  'US/Alaska',
  'US/Aleutian',
  'US/Arizona',
  'US/Central',
  'US/East-Indiana',
  'US/Eastern',
  'US/Hawaii',
  'US/Indiana-Starke',
  'US/Michigan',
  'US/Mountain',
  'US/Pacific',
  'US/Samoa',
};

/// Returns the [Timezone] associated with the given [name] if it exists. Otherwise returns the `Factory` [Timezone].
/// 
/// ## Implementation details:
/// To lazily initialize [Timezone]s, a switch statement is used instead of a [Map].
/// Since most use-cases only require a few [Timezone]s, it drastically reduces memory footprint.
@internal Timezone parseTimezone(String timezone) {
  switch (timezone) {

    case 'CET':
      return Root.cet;
    case 'CST6CDT':
      return Root.cst6cdt;
    case 'Cuba':
      return Root.cuba;
    case 'EET':
      return Root.eet;
    case 'EST':
      return Root.est;
    case 'EST5EDT':
      return Root.est5edt;
    case 'Egypt':
      return Root.egypt;
    case 'Eire':
      return Root.eire;
    case 'Factory':
      return Root.factory;
    case 'GB':
      return Root.gb;
    case 'GB-Eire':
      return Root.gbEire;
    case 'GMT':
      return Root.gmt;
    case 'GMT+0':
      return Root.gmtPlus0;
    case 'GMT-0':
      return Root.gmtMinus0;
    case 'GMT0':
      return Root.gmt0;
    case 'Greenwich':
      return Root.greenwich;
    case 'HST':
      return Root.hst;
    case 'Hongkong':
      return Root.hongkong;
    case 'Iceland':
      return Root.iceland;
    case 'Iran':
      return Root.iran;
    case 'Israel':
      return Root.israel;
    case 'Jamaica':
      return Root.jamaica;
    case 'Japan':
      return Root.japan;
    case 'Kwajalein':
      return Root.kwajalein;
    case 'Libya':
      return Root.libya;
    case 'MET':
      return Root.met;
    case 'MST':
      return Root.mst;
    case 'MST7MDT':
      return Root.mst7mdt;
    case 'NZ':
      return Root.nz;
    case 'NZ-CHAT':
      return Root.nzChat;
    case 'Navajo':
      return Root.navajo;
    case 'PRC':
      return Root.prc;
    case 'PST8PDT':
      return Root.pst8pdt;
    case 'Poland':
      return Root.poland;
    case 'Portugal':
      return Root.portugal;
    case 'ROC':
      return Root.roc;
    case 'ROK':
      return Root.rok;
    case 'Singapore':
      return Root.singapore;
    case 'Turkey':
      return Root.turkey;
    case 'UCT':
      return Root.uct;
    case 'UTC':
      return Root.utc;
    case 'Universal':
      return Root.universal;
    case 'W-SU':
      return Root.wSu;
    case 'WET':
      return Root.wet;
    case 'Zulu':
      return Root.zulu;
    case 'Africa/Abidjan':
      return Africa.abidjan;
    case 'Africa/Accra':
      return Africa.accra;
    case 'Africa/Addis_Ababa':
      return Africa.addisAbaba;
    case 'Africa/Algiers':
      return Africa.algiers;
    case 'Africa/Asmara':
      return Africa.asmara;
    case 'Africa/Asmera':
      return Africa.asmera;
    case 'Africa/Bamako':
      return Africa.bamako;
    case 'Africa/Bangui':
      return Africa.bangui;
    case 'Africa/Banjul':
      return Africa.banjul;
    case 'Africa/Bissau':
      return Africa.bissau;
    case 'Africa/Blantyre':
      return Africa.blantyre;
    case 'Africa/Brazzaville':
      return Africa.brazzaville;
    case 'Africa/Bujumbura':
      return Africa.bujumbura;
    case 'Africa/Cairo':
      return Africa.cairo;
    case 'Africa/Casablanca':
      return Africa.casablanca;
    case 'Africa/Ceuta':
      return Africa.ceuta;
    case 'Africa/Conakry':
      return Africa.conakry;
    case 'Africa/Dakar':
      return Africa.dakar;
    case 'Africa/Dar_es_Salaam':
      return Africa.darEsSalaam;
    case 'Africa/Djibouti':
      return Africa.djibouti;
    case 'Africa/Douala':
      return Africa.douala;
    case 'Africa/El_Aaiun':
      return Africa.elAaiun;
    case 'Africa/Freetown':
      return Africa.freetown;
    case 'Africa/Gaborone':
      return Africa.gaborone;
    case 'Africa/Harare':
      return Africa.harare;
    case 'Africa/Johannesburg':
      return Africa.johannesburg;
    case 'Africa/Juba':
      return Africa.juba;
    case 'Africa/Kampala':
      return Africa.kampala;
    case 'Africa/Khartoum':
      return Africa.khartoum;
    case 'Africa/Kigali':
      return Africa.kigali;
    case 'Africa/Kinshasa':
      return Africa.kinshasa;
    case 'Africa/Lagos':
      return Africa.lagos;
    case 'Africa/Libreville':
      return Africa.libreville;
    case 'Africa/Lome':
      return Africa.lome;
    case 'Africa/Luanda':
      return Africa.luanda;
    case 'Africa/Lubumbashi':
      return Africa.lubumbashi;
    case 'Africa/Lusaka':
      return Africa.lusaka;
    case 'Africa/Malabo':
      return Africa.malabo;
    case 'Africa/Maputo':
      return Africa.maputo;
    case 'Africa/Maseru':
      return Africa.maseru;
    case 'Africa/Mbabane':
      return Africa.mbabane;
    case 'Africa/Mogadishu':
      return Africa.mogadishu;
    case 'Africa/Monrovia':
      return Africa.monrovia;
    case 'Africa/Nairobi':
      return Africa.nairobi;
    case 'Africa/Ndjamena':
      return Africa.ndjamena;
    case 'Africa/Niamey':
      return Africa.niamey;
    case 'Africa/Nouakchott':
      return Africa.nouakchott;
    case 'Africa/Ouagadougou':
      return Africa.ouagadougou;
    case 'Africa/Porto-Novo':
      return Africa.portoNovo;
    case 'Africa/Sao_Tome':
      return Africa.saoTome;
    case 'Africa/Timbuktu':
      return Africa.timbuktu;
    case 'Africa/Tripoli':
      return Africa.tripoli;
    case 'Africa/Tunis':
      return Africa.tunis;
    case 'Africa/Windhoek':
      return Africa.windhoek;
    case 'America/Adak':
      return America.adak;
    case 'America/Anchorage':
      return America.anchorage;
    case 'America/Anguilla':
      return America.anguilla;
    case 'America/Antigua':
      return America.antigua;
    case 'America/Araguaina':
      return America.araguaina;
    case 'America/Aruba':
      return America.aruba;
    case 'America/Asuncion':
      return America.asuncion;
    case 'America/Atikokan':
      return America.atikokan;
    case 'America/Atka':
      return America.atka;
    case 'America/Bahia':
      return America.bahia;
    case 'America/Bahia_Banderas':
      return America.bahiaBanderas;
    case 'America/Barbados':
      return America.barbados;
    case 'America/Belem':
      return America.belem;
    case 'America/Belize':
      return America.belize;
    case 'America/Blanc-Sablon':
      return America.blancSablon;
    case 'America/Boa_Vista':
      return America.boaVista;
    case 'America/Bogota':
      return America.bogota;
    case 'America/Boise':
      return America.boise;
    case 'America/Buenos_Aires':
      return America.buenosAires;
    case 'America/Cambridge_Bay':
      return America.cambridgeBay;
    case 'America/Campo_Grande':
      return America.campoGrande;
    case 'America/Cancun':
      return America.cancun;
    case 'America/Caracas':
      return America.caracas;
    case 'America/Catamarca':
      return America.catamarca;
    case 'America/Cayenne':
      return America.cayenne;
    case 'America/Cayman':
      return America.cayman;
    case 'America/Chicago':
      return America.chicago;
    case 'America/Chihuahua':
      return America.chihuahua;
    case 'America/Ciudad_Juarez':
      return America.ciudadJuarez;
    case 'America/Coral_Harbour':
      return America.coralHarbour;
    case 'America/Cordoba':
      return America.cordoba;
    case 'America/Costa_Rica':
      return America.costaRica;
    case 'America/Creston':
      return America.creston;
    case 'America/Cuiaba':
      return America.cuiaba;
    case 'America/Curacao':
      return America.curacao;
    case 'America/Danmarkshavn':
      return America.danmarkshavn;
    case 'America/Dawson':
      return America.dawson;
    case 'America/Dawson_Creek':
      return America.dawsonCreek;
    case 'America/Denver':
      return America.denver;
    case 'America/Detroit':
      return America.detroit;
    case 'America/Dominica':
      return America.dominica;
    case 'America/Edmonton':
      return America.edmonton;
    case 'America/Eirunepe':
      return America.eirunepe;
    case 'America/El_Salvador':
      return America.elSalvador;
    case 'America/Ensenada':
      return America.ensenada;
    case 'America/Fort_Nelson':
      return America.fortNelson;
    case 'America/Fort_Wayne':
      return America.fortWayne;
    case 'America/Fortaleza':
      return America.fortaleza;
    case 'America/Glace_Bay':
      return America.glaceBay;
    case 'America/Godthab':
      return America.godthab;
    case 'America/Goose_Bay':
      return America.gooseBay;
    case 'America/Grand_Turk':
      return America.grandTurk;
    case 'America/Grenada':
      return America.grenada;
    case 'America/Guadeloupe':
      return America.guadeloupe;
    case 'America/Guatemala':
      return America.guatemala;
    case 'America/Guayaquil':
      return America.guayaquil;
    case 'America/Guyana':
      return America.guyana;
    case 'America/Halifax':
      return America.halifax;
    case 'America/Havana':
      return America.havana;
    case 'America/Hermosillo':
      return America.hermosillo;
    case 'America/Indianapolis':
      return America.indianapolis;
    case 'America/Inuvik':
      return America.inuvik;
    case 'America/Iqaluit':
      return America.iqaluit;
    case 'America/Jamaica':
      return America.jamaica;
    case 'America/Jujuy':
      return America.jujuy;
    case 'America/Juneau':
      return America.juneau;
    case 'America/Knox_IN':
      return America.knoxIn;
    case 'America/Kralendijk':
      return America.kralendijk;
    case 'America/La_Paz':
      return America.laPaz;
    case 'America/Lima':
      return America.lima;
    case 'America/Los_Angeles':
      return America.losAngeles;
    case 'America/Louisville':
      return America.louisville;
    case 'America/Lower_Princes':
      return America.lowerPrinces;
    case 'America/Maceio':
      return America.maceio;
    case 'America/Managua':
      return America.managua;
    case 'America/Manaus':
      return America.manaus;
    case 'America/Marigot':
      return America.marigot;
    case 'America/Martinique':
      return America.martinique;
    case 'America/Matamoros':
      return America.matamoros;
    case 'America/Mazatlan':
      return America.mazatlan;
    case 'America/Mendoza':
      return America.mendoza;
    case 'America/Menominee':
      return America.menominee;
    case 'America/Merida':
      return America.merida;
    case 'America/Metlakatla':
      return America.metlakatla;
    case 'America/Mexico_City':
      return America.mexicoCity;
    case 'America/Miquelon':
      return America.miquelon;
    case 'America/Moncton':
      return America.moncton;
    case 'America/Monterrey':
      return America.monterrey;
    case 'America/Montevideo':
      return America.montevideo;
    case 'America/Montreal':
      return America.montreal;
    case 'America/Montserrat':
      return America.montserrat;
    case 'America/Nassau':
      return America.nassau;
    case 'America/New_York':
      return America.newYork;
    case 'America/Nipigon':
      return America.nipigon;
    case 'America/Nome':
      return America.nome;
    case 'America/Noronha':
      return America.noronha;
    case 'America/Nuuk':
      return America.nuuk;
    case 'America/Ojinaga':
      return America.ojinaga;
    case 'America/Panama':
      return America.panama;
    case 'America/Pangnirtung':
      return America.pangnirtung;
    case 'America/Paramaribo':
      return America.paramaribo;
    case 'America/Phoenix':
      return America.phoenix;
    case 'America/Port-au-Prince':
      return America.portAuPrince;
    case 'America/Port_of_Spain':
      return America.portOfSpain;
    case 'America/Porto_Acre':
      return America.portoAcre;
    case 'America/Porto_Velho':
      return America.portoVelho;
    case 'America/Puerto_Rico':
      return America.puertoRico;
    case 'America/Punta_Arenas':
      return America.puntaArenas;
    case 'America/Rainy_River':
      return America.rainyRiver;
    case 'America/Rankin_Inlet':
      return America.rankinInlet;
    case 'America/Recife':
      return America.recife;
    case 'America/Regina':
      return America.regina;
    case 'America/Resolute':
      return America.resolute;
    case 'America/Rio_Branco':
      return America.rioBranco;
    case 'America/Rosario':
      return America.rosario;
    case 'America/Santa_Isabel':
      return America.santaIsabel;
    case 'America/Santarem':
      return America.santarem;
    case 'America/Santiago':
      return America.santiago;
    case 'America/Santo_Domingo':
      return America.santoDomingo;
    case 'America/Sao_Paulo':
      return America.saoPaulo;
    case 'America/Scoresbysund':
      return America.scoresbysund;
    case 'America/Shiprock':
      return America.shiprock;
    case 'America/Sitka':
      return America.sitka;
    case 'America/St_Barthelemy':
      return America.stBarthelemy;
    case 'America/St_Johns':
      return America.stJohns;
    case 'America/St_Kitts':
      return America.stKitts;
    case 'America/St_Lucia':
      return America.stLucia;
    case 'America/St_Thomas':
      return America.stThomas;
    case 'America/St_Vincent':
      return America.stVincent;
    case 'America/Swift_Current':
      return America.swiftCurrent;
    case 'America/Tegucigalpa':
      return America.tegucigalpa;
    case 'America/Thule':
      return America.thule;
    case 'America/Thunder_Bay':
      return America.thunderBay;
    case 'America/Tijuana':
      return America.tijuana;
    case 'America/Toronto':
      return America.toronto;
    case 'America/Tortola':
      return America.tortola;
    case 'America/Vancouver':
      return America.vancouver;
    case 'America/Virgin':
      return America.virgin;
    case 'America/Whitehorse':
      return America.whitehorse;
    case 'America/Winnipeg':
      return America.winnipeg;
    case 'America/Yakutat':
      return America.yakutat;
    case 'America/Yellowknife':
      return America.yellowknife;
    case 'America/Argentina/Buenos_Aires':
      return Argentina.buenosAires;
    case 'America/Argentina/Catamarca':
      return Argentina.catamarca;
    case 'America/Argentina/ComodRivadavia':
      return Argentina.comodRivadavia;
    case 'America/Argentina/Cordoba':
      return Argentina.cordoba;
    case 'America/Argentina/Jujuy':
      return Argentina.jujuy;
    case 'America/Argentina/La_Rioja':
      return Argentina.laRioja;
    case 'America/Argentina/Mendoza':
      return Argentina.mendoza;
    case 'America/Argentina/Rio_Gallegos':
      return Argentina.rioGallegos;
    case 'America/Argentina/Salta':
      return Argentina.salta;
    case 'America/Argentina/San_Juan':
      return Argentina.sanJuan;
    case 'America/Argentina/San_Luis':
      return Argentina.sanLuis;
    case 'America/Argentina/Tucuman':
      return Argentina.tucuman;
    case 'America/Argentina/Ushuaia':
      return Argentina.ushuaia;
    case 'America/Indiana/Indianapolis':
      return Indiana.indianapolis;
    case 'America/Indiana/Knox':
      return Indiana.knox;
    case 'America/Indiana/Marengo':
      return Indiana.marengo;
    case 'America/Indiana/Petersburg':
      return Indiana.petersburg;
    case 'America/Indiana/Tell_City':
      return Indiana.tellCity;
    case 'America/Indiana/Vevay':
      return Indiana.vevay;
    case 'America/Indiana/Vincennes':
      return Indiana.vincennes;
    case 'America/Indiana/Winamac':
      return Indiana.winamac;
    case 'America/Kentucky/Louisville':
      return Kentucky.louisville;
    case 'America/Kentucky/Monticello':
      return Kentucky.monticello;
    case 'America/North_Dakota/Beulah':
      return NorthDakota.beulah;
    case 'America/North_Dakota/Center':
      return NorthDakota.center;
    case 'America/North_Dakota/New_Salem':
      return NorthDakota.newSalem;
    case 'Antarctica/Casey':
      return Antarctica.casey;
    case 'Antarctica/Davis':
      return Antarctica.davis;
    case 'Antarctica/DumontDUrville':
      return Antarctica.dumontDUrville;
    case 'Antarctica/Macquarie':
      return Antarctica.macquarie;
    case 'Antarctica/Mawson':
      return Antarctica.mawson;
    case 'Antarctica/McMurdo':
      return Antarctica.mcMurdo;
    case 'Antarctica/Palmer':
      return Antarctica.palmer;
    case 'Antarctica/Rothera':
      return Antarctica.rothera;
    case 'Antarctica/South_Pole':
      return Antarctica.southPole;
    case 'Antarctica/Syowa':
      return Antarctica.syowa;
    case 'Antarctica/Troll':
      return Antarctica.troll;
    case 'Antarctica/Vostok':
      return Antarctica.vostok;
    case 'Arctic/Longyearbyen':
      return Arctic.longyearbyen;
    case 'Asia/Aden':
      return Asia.aden;
    case 'Asia/Almaty':
      return Asia.almaty;
    case 'Asia/Amman':
      return Asia.amman;
    case 'Asia/Anadyr':
      return Asia.anadyr;
    case 'Asia/Aqtau':
      return Asia.aqtau;
    case 'Asia/Aqtobe':
      return Asia.aqtobe;
    case 'Asia/Ashgabat':
      return Asia.ashgabat;
    case 'Asia/Ashkhabad':
      return Asia.ashkhabad;
    case 'Asia/Atyrau':
      return Asia.atyrau;
    case 'Asia/Baghdad':
      return Asia.baghdad;
    case 'Asia/Bahrain':
      return Asia.bahrain;
    case 'Asia/Baku':
      return Asia.baku;
    case 'Asia/Bangkok':
      return Asia.bangkok;
    case 'Asia/Barnaul':
      return Asia.barnaul;
    case 'Asia/Beirut':
      return Asia.beirut;
    case 'Asia/Bishkek':
      return Asia.bishkek;
    case 'Asia/Brunei':
      return Asia.brunei;
    case 'Asia/Calcutta':
      return Asia.calcutta;
    case 'Asia/Chita':
      return Asia.chita;
    case 'Asia/Choibalsan':
      return Asia.choibalsan;
    case 'Asia/Chongqing':
      return Asia.chongqing;
    case 'Asia/Chungking':
      return Asia.chungking;
    case 'Asia/Colombo':
      return Asia.colombo;
    case 'Asia/Dacca':
      return Asia.dacca;
    case 'Asia/Damascus':
      return Asia.damascus;
    case 'Asia/Dhaka':
      return Asia.dhaka;
    case 'Asia/Dili':
      return Asia.dili;
    case 'Asia/Dubai':
      return Asia.dubai;
    case 'Asia/Dushanbe':
      return Asia.dushanbe;
    case 'Asia/Famagusta':
      return Asia.famagusta;
    case 'Asia/Gaza':
      return Asia.gaza;
    case 'Asia/Harbin':
      return Asia.harbin;
    case 'Asia/Hebron':
      return Asia.hebron;
    case 'Asia/Ho_Chi_Minh':
      return Asia.hoChiMinh;
    case 'Asia/Hong_Kong':
      return Asia.hongKong;
    case 'Asia/Hovd':
      return Asia.hovd;
    case 'Asia/Irkutsk':
      return Asia.irkutsk;
    case 'Asia/Istanbul':
      return Asia.istanbul;
    case 'Asia/Jakarta':
      return Asia.jakarta;
    case 'Asia/Jayapura':
      return Asia.jayapura;
    case 'Asia/Jerusalem':
      return Asia.jerusalem;
    case 'Asia/Kabul':
      return Asia.kabul;
    case 'Asia/Kamchatka':
      return Asia.kamchatka;
    case 'Asia/Karachi':
      return Asia.karachi;
    case 'Asia/Kashgar':
      return Asia.kashgar;
    case 'Asia/Kathmandu':
      return Asia.kathmandu;
    case 'Asia/Katmandu':
      return Asia.katmandu;
    case 'Asia/Khandyga':
      return Asia.khandyga;
    case 'Asia/Kolkata':
      return Asia.kolkata;
    case 'Asia/Krasnoyarsk':
      return Asia.krasnoyarsk;
    case 'Asia/Kuala_Lumpur':
      return Asia.kualaLumpur;
    case 'Asia/Kuching':
      return Asia.kuching;
    case 'Asia/Kuwait':
      return Asia.kuwait;
    case 'Asia/Macao':
      return Asia.macao;
    case 'Asia/Macau':
      return Asia.macau;
    case 'Asia/Magadan':
      return Asia.magadan;
    case 'Asia/Makassar':
      return Asia.makassar;
    case 'Asia/Manila':
      return Asia.manila;
    case 'Asia/Muscat':
      return Asia.muscat;
    case 'Asia/Nicosia':
      return Asia.nicosia;
    case 'Asia/Novokuznetsk':
      return Asia.novokuznetsk;
    case 'Asia/Novosibirsk':
      return Asia.novosibirsk;
    case 'Asia/Omsk':
      return Asia.omsk;
    case 'Asia/Oral':
      return Asia.oral;
    case 'Asia/Phnom_Penh':
      return Asia.phnomPenh;
    case 'Asia/Pontianak':
      return Asia.pontianak;
    case 'Asia/Pyongyang':
      return Asia.pyongyang;
    case 'Asia/Qatar':
      return Asia.qatar;
    case 'Asia/Qostanay':
      return Asia.qostanay;
    case 'Asia/Qyzylorda':
      return Asia.qyzylorda;
    case 'Asia/Rangoon':
      return Asia.rangoon;
    case 'Asia/Riyadh':
      return Asia.riyadh;
    case 'Asia/Saigon':
      return Asia.saigon;
    case 'Asia/Sakhalin':
      return Asia.sakhalin;
    case 'Asia/Samarkand':
      return Asia.samarkand;
    case 'Asia/Seoul':
      return Asia.seoul;
    case 'Asia/Shanghai':
      return Asia.shanghai;
    case 'Asia/Singapore':
      return Asia.singapore;
    case 'Asia/Srednekolymsk':
      return Asia.srednekolymsk;
    case 'Asia/Taipei':
      return Asia.taipei;
    case 'Asia/Tashkent':
      return Asia.tashkent;
    case 'Asia/Tbilisi':
      return Asia.tbilisi;
    case 'Asia/Tehran':
      return Asia.tehran;
    case 'Asia/Tel_Aviv':
      return Asia.telAviv;
    case 'Asia/Thimbu':
      return Asia.thimbu;
    case 'Asia/Thimphu':
      return Asia.thimphu;
    case 'Asia/Tokyo':
      return Asia.tokyo;
    case 'Asia/Tomsk':
      return Asia.tomsk;
    case 'Asia/Ujung_Pandang':
      return Asia.ujungPandang;
    case 'Asia/Ulaanbaatar':
      return Asia.ulaanbaatar;
    case 'Asia/Ulan_Bator':
      return Asia.ulanBator;
    case 'Asia/Urumqi':
      return Asia.urumqi;
    case 'Asia/Ust-Nera':
      return Asia.ustNera;
    case 'Asia/Vientiane':
      return Asia.vientiane;
    case 'Asia/Vladivostok':
      return Asia.vladivostok;
    case 'Asia/Yakutsk':
      return Asia.yakutsk;
    case 'Asia/Yangon':
      return Asia.yangon;
    case 'Asia/Yekaterinburg':
      return Asia.yekaterinburg;
    case 'Asia/Yerevan':
      return Asia.yerevan;
    case 'Atlantic/Azores':
      return Atlantic.azores;
    case 'Atlantic/Bermuda':
      return Atlantic.bermuda;
    case 'Atlantic/Canary':
      return Atlantic.canary;
    case 'Atlantic/Cape_Verde':
      return Atlantic.capeVerde;
    case 'Atlantic/Faeroe':
      return Atlantic.faeroe;
    case 'Atlantic/Faroe':
      return Atlantic.faroe;
    case 'Atlantic/Jan_Mayen':
      return Atlantic.janMayen;
    case 'Atlantic/Madeira':
      return Atlantic.madeira;
    case 'Atlantic/Reykjavik':
      return Atlantic.reykjavik;
    case 'Atlantic/South_Georgia':
      return Atlantic.southGeorgia;
    case 'Atlantic/St_Helena':
      return Atlantic.stHelena;
    case 'Atlantic/Stanley':
      return Atlantic.stanley;
    case 'Australia/ACT':
      return Australia.act;
    case 'Australia/Adelaide':
      return Australia.adelaide;
    case 'Australia/Brisbane':
      return Australia.brisbane;
    case 'Australia/Broken_Hill':
      return Australia.brokenHill;
    case 'Australia/Canberra':
      return Australia.canberra;
    case 'Australia/Currie':
      return Australia.currie;
    case 'Australia/Darwin':
      return Australia.darwin;
    case 'Australia/Eucla':
      return Australia.eucla;
    case 'Australia/Hobart':
      return Australia.hobart;
    case 'Australia/LHI':
      return Australia.lhi;
    case 'Australia/Lindeman':
      return Australia.lindeman;
    case 'Australia/Lord_Howe':
      return Australia.lordHowe;
    case 'Australia/Melbourne':
      return Australia.melbourne;
    case 'Australia/NSW':
      return Australia.nsw;
    case 'Australia/North':
      return Australia.north;
    case 'Australia/Perth':
      return Australia.perth;
    case 'Australia/Queensland':
      return Australia.queensland;
    case 'Australia/South':
      return Australia.south;
    case 'Australia/Sydney':
      return Australia.sydney;
    case 'Australia/Tasmania':
      return Australia.tasmania;
    case 'Australia/Victoria':
      return Australia.victoria;
    case 'Australia/West':
      return Australia.west;
    case 'Australia/Yancowinna':
      return Australia.yancowinna;
    case 'Brazil/Acre':
      return Brazil.acre;
    case 'Brazil/DeNoronha':
      return Brazil.deNoronha;
    case 'Brazil/East':
      return Brazil.east;
    case 'Brazil/West':
      return Brazil.west;
    case 'Canada/Atlantic':
      return Canada.atlantic;
    case 'Canada/Central':
      return Canada.central;
    case 'Canada/Eastern':
      return Canada.eastern;
    case 'Canada/Mountain':
      return Canada.mountain;
    case 'Canada/Newfoundland':
      return Canada.newfoundland;
    case 'Canada/Pacific':
      return Canada.pacific;
    case 'Canada/Saskatchewan':
      return Canada.saskatchewan;
    case 'Canada/Yukon':
      return Canada.yukon;
    case 'Chile/Continental':
      return Chile.continental;
    case 'Chile/EasterIsland':
      return Chile.easterIsland;
    case 'Etc/GMT':
      return Etc.gmt;
    case 'Etc/GMT+0':
      return Etc.gmtPlus0;
    case 'Etc/GMT+1':
      return Etc.gmtPlus1;
    case 'Etc/GMT+10':
      return Etc.gmtPlus10;
    case 'Etc/GMT+11':
      return Etc.gmtPlus11;
    case 'Etc/GMT+12':
      return Etc.gmtPlus12;
    case 'Etc/GMT+2':
      return Etc.gmtPlus2;
    case 'Etc/GMT+3':
      return Etc.gmtPlus3;
    case 'Etc/GMT+4':
      return Etc.gmtPlus4;
    case 'Etc/GMT+5':
      return Etc.gmtPlus5;
    case 'Etc/GMT+6':
      return Etc.gmtPlus6;
    case 'Etc/GMT+7':
      return Etc.gmtPlus7;
    case 'Etc/GMT+8':
      return Etc.gmtPlus8;
    case 'Etc/GMT+9':
      return Etc.gmtPlus9;
    case 'Etc/GMT-0':
      return Etc.gmtMinus0;
    case 'Etc/GMT-1':
      return Etc.gmtMinus1;
    case 'Etc/GMT-10':
      return Etc.gmtMinus10;
    case 'Etc/GMT-11':
      return Etc.gmtMinus11;
    case 'Etc/GMT-12':
      return Etc.gmtMinus12;
    case 'Etc/GMT-13':
      return Etc.gmtMinus13;
    case 'Etc/GMT-14':
      return Etc.gmtMinus14;
    case 'Etc/GMT-2':
      return Etc.gmtMinus2;
    case 'Etc/GMT-3':
      return Etc.gmtMinus3;
    case 'Etc/GMT-4':
      return Etc.gmtMinus4;
    case 'Etc/GMT-5':
      return Etc.gmtMinus5;
    case 'Etc/GMT-6':
      return Etc.gmtMinus6;
    case 'Etc/GMT-7':
      return Etc.gmtMinus7;
    case 'Etc/GMT-8':
      return Etc.gmtMinus8;
    case 'Etc/GMT-9':
      return Etc.gmtMinus9;
    case 'Etc/GMT0':
      return Etc.gmt0;
    case 'Etc/Greenwich':
      return Etc.greenwich;
    case 'Etc/UCT':
      return Etc.uct;
    case 'Etc/UTC':
      return Etc.utc;
    case 'Etc/Universal':
      return Etc.universal;
    case 'Etc/Zulu':
      return Etc.zulu;
    case 'Europe/Amsterdam':
      return Europe.amsterdam;
    case 'Europe/Andorra':
      return Europe.andorra;
    case 'Europe/Astrakhan':
      return Europe.astrakhan;
    case 'Europe/Athens':
      return Europe.athens;
    case 'Europe/Belfast':
      return Europe.belfast;
    case 'Europe/Belgrade':
      return Europe.belgrade;
    case 'Europe/Berlin':
      return Europe.berlin;
    case 'Europe/Bratislava':
      return Europe.bratislava;
    case 'Europe/Brussels':
      return Europe.brussels;
    case 'Europe/Bucharest':
      return Europe.bucharest;
    case 'Europe/Budapest':
      return Europe.budapest;
    case 'Europe/Busingen':
      return Europe.busingen;
    case 'Europe/Chisinau':
      return Europe.chisinau;
    case 'Europe/Copenhagen':
      return Europe.copenhagen;
    case 'Europe/Dublin':
      return Europe.dublin;
    case 'Europe/Gibraltar':
      return Europe.gibraltar;
    case 'Europe/Guernsey':
      return Europe.guernsey;
    case 'Europe/Helsinki':
      return Europe.helsinki;
    case 'Europe/Isle_of_Man':
      return Europe.isleOfMan;
    case 'Europe/Istanbul':
      return Europe.istanbul;
    case 'Europe/Jersey':
      return Europe.jersey;
    case 'Europe/Kaliningrad':
      return Europe.kaliningrad;
    case 'Europe/Kiev':
      return Europe.kiev;
    case 'Europe/Kirov':
      return Europe.kirov;
    case 'Europe/Kyiv':
      return Europe.kyiv;
    case 'Europe/Lisbon':
      return Europe.lisbon;
    case 'Europe/Ljubljana':
      return Europe.ljubljana;
    case 'Europe/London':
      return Europe.london;
    case 'Europe/Luxembourg':
      return Europe.luxembourg;
    case 'Europe/Madrid':
      return Europe.madrid;
    case 'Europe/Malta':
      return Europe.malta;
    case 'Europe/Mariehamn':
      return Europe.mariehamn;
    case 'Europe/Minsk':
      return Europe.minsk;
    case 'Europe/Monaco':
      return Europe.monaco;
    case 'Europe/Moscow':
      return Europe.moscow;
    case 'Europe/Nicosia':
      return Europe.nicosia;
    case 'Europe/Oslo':
      return Europe.oslo;
    case 'Europe/Paris':
      return Europe.paris;
    case 'Europe/Podgorica':
      return Europe.podgorica;
    case 'Europe/Prague':
      return Europe.prague;
    case 'Europe/Riga':
      return Europe.riga;
    case 'Europe/Rome':
      return Europe.rome;
    case 'Europe/Samara':
      return Europe.samara;
    case 'Europe/San_Marino':
      return Europe.sanMarino;
    case 'Europe/Sarajevo':
      return Europe.sarajevo;
    case 'Europe/Saratov':
      return Europe.saratov;
    case 'Europe/Simferopol':
      return Europe.simferopol;
    case 'Europe/Skopje':
      return Europe.skopje;
    case 'Europe/Sofia':
      return Europe.sofia;
    case 'Europe/Stockholm':
      return Europe.stockholm;
    case 'Europe/Tallinn':
      return Europe.tallinn;
    case 'Europe/Tirane':
      return Europe.tirane;
    case 'Europe/Tiraspol':
      return Europe.tiraspol;
    case 'Europe/Ulyanovsk':
      return Europe.ulyanovsk;
    case 'Europe/Uzhgorod':
      return Europe.uzhgorod;
    case 'Europe/Vaduz':
      return Europe.vaduz;
    case 'Europe/Vatican':
      return Europe.vatican;
    case 'Europe/Vienna':
      return Europe.vienna;
    case 'Europe/Vilnius':
      return Europe.vilnius;
    case 'Europe/Volgograd':
      return Europe.volgograd;
    case 'Europe/Warsaw':
      return Europe.warsaw;
    case 'Europe/Zagreb':
      return Europe.zagreb;
    case 'Europe/Zaporozhye':
      return Europe.zaporozhye;
    case 'Europe/Zurich':
      return Europe.zurich;
    case 'Indian/Antananarivo':
      return Indian.antananarivo;
    case 'Indian/Chagos':
      return Indian.chagos;
    case 'Indian/Christmas':
      return Indian.christmas;
    case 'Indian/Cocos':
      return Indian.cocos;
    case 'Indian/Comoro':
      return Indian.comoro;
    case 'Indian/Kerguelen':
      return Indian.kerguelen;
    case 'Indian/Mahe':
      return Indian.mahe;
    case 'Indian/Maldives':
      return Indian.maldives;
    case 'Indian/Mauritius':
      return Indian.mauritius;
    case 'Indian/Mayotte':
      return Indian.mayotte;
    case 'Indian/Reunion':
      return Indian.reunion;
    case 'Mexico/BajaNorte':
      return Mexico.bajaNorte;
    case 'Mexico/BajaSur':
      return Mexico.bajaSur;
    case 'Mexico/General':
      return Mexico.general;
    case 'Pacific/Apia':
      return Pacific.apia;
    case 'Pacific/Auckland':
      return Pacific.auckland;
    case 'Pacific/Bougainville':
      return Pacific.bougainville;
    case 'Pacific/Chatham':
      return Pacific.chatham;
    case 'Pacific/Chuuk':
      return Pacific.chuuk;
    case 'Pacific/Easter':
      return Pacific.easter;
    case 'Pacific/Efate':
      return Pacific.efate;
    case 'Pacific/Enderbury':
      return Pacific.enderbury;
    case 'Pacific/Fakaofo':
      return Pacific.fakaofo;
    case 'Pacific/Fiji':
      return Pacific.fiji;
    case 'Pacific/Funafuti':
      return Pacific.funafuti;
    case 'Pacific/Galapagos':
      return Pacific.galapagos;
    case 'Pacific/Gambier':
      return Pacific.gambier;
    case 'Pacific/Guadalcanal':
      return Pacific.guadalcanal;
    case 'Pacific/Guam':
      return Pacific.guam;
    case 'Pacific/Honolulu':
      return Pacific.honolulu;
    case 'Pacific/Johnston':
      return Pacific.johnston;
    case 'Pacific/Kanton':
      return Pacific.kanton;
    case 'Pacific/Kiritimati':
      return Pacific.kiritimati;
    case 'Pacific/Kosrae':
      return Pacific.kosrae;
    case 'Pacific/Kwajalein':
      return Pacific.kwajalein;
    case 'Pacific/Majuro':
      return Pacific.majuro;
    case 'Pacific/Marquesas':
      return Pacific.marquesas;
    case 'Pacific/Midway':
      return Pacific.midway;
    case 'Pacific/Nauru':
      return Pacific.nauru;
    case 'Pacific/Niue':
      return Pacific.niue;
    case 'Pacific/Norfolk':
      return Pacific.norfolk;
    case 'Pacific/Noumea':
      return Pacific.noumea;
    case 'Pacific/Pago_Pago':
      return Pacific.pagoPago;
    case 'Pacific/Palau':
      return Pacific.palau;
    case 'Pacific/Pitcairn':
      return Pacific.pitcairn;
    case 'Pacific/Pohnpei':
      return Pacific.pohnpei;
    case 'Pacific/Ponape':
      return Pacific.ponape;
    case 'Pacific/Port_Moresby':
      return Pacific.portMoresby;
    case 'Pacific/Rarotonga':
      return Pacific.rarotonga;
    case 'Pacific/Saipan':
      return Pacific.saipan;
    case 'Pacific/Samoa':
      return Pacific.samoa;
    case 'Pacific/Tahiti':
      return Pacific.tahiti;
    case 'Pacific/Tarawa':
      return Pacific.tarawa;
    case 'Pacific/Tongatapu':
      return Pacific.tongatapu;
    case 'Pacific/Truk':
      return Pacific.truk;
    case 'Pacific/Wake':
      return Pacific.wake;
    case 'Pacific/Wallis':
      return Pacific.wallis;
    case 'Pacific/Yap':
      return Pacific.yap;
    case 'US/Alaska':
      return Us.alaska;
    case 'US/Aleutian':
      return Us.aleutian;
    case 'US/Arizona':
      return Us.arizona;
    case 'US/Central':
      return Us.central;
    case 'US/East-Indiana':
      return Us.eastIndiana;
    case 'US/Eastern':
      return Us.eastern;
    case 'US/Hawaii':
      return Us.hawaii;
    case 'US/Indiana-Starke':
      return Us.indianaStarke;
    case 'US/Michigan':
      return Us.michigan;
    case 'US/Mountain':
      return Us.mountain;
    case 'US/Pacific':
      return Us.pacific;
    case 'US/Samoa':
      return Us.samoa;
    default:
      return Root.factory;
  }
}
