include: package:flint/analysis_options.dart.yaml
linter:
  rules:
    avoid_equals_and_hash_code_on_mutable_classes: false

analyzer:
  errors:
    unused_result: ignore # The rule seems to break almost every release.
  exclude:
    - lib/src/time/zone/info/**
    - test/src/time/zone/providers/embedded/java_provider/bindings.dart
    - misc/**
    - out/**