// GENERATED CODE - DO NOT MODIFY BY HAND
//
// **************************************************************************
// Generated by: sugar/tool/timezone/generate_timezones.dart
// **************************************************************************
// 
// ignore_for_file: type=lint

import 'dart:typed_data';

import 'package:sugar/src/time/offset.dart';
import 'package:sugar/src/time/zone/dynamic_timezone.dart';
import 'package:sugar/src/time/zone/fixed_timezone.dart';
import 'package:sugar/src/time/zone/timezone.dart';
import 'package:sugar/src/time/zone/timezone_span.dart';

extension Etc on Never {
  static final Timezone gmt = FixedTimezone(
    'Etc/GMT',
    FixedTimezoneSpan(
      const LiteralOffset('Z', 0),
      'GMT',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtPlus0 = FixedTimezone(
    'Etc/GMT+0',
    FixedTimezoneSpan(
      const LiteralOffset('Z', 0),
      'GMT',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtPlus1 = FixedTimezone(
    'Etc/GMT+1',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', -3600),
      '-01',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtPlus10 = FixedTimezone(
    'Etc/GMT+10',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', -36000),
      '-10',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtPlus11 = FixedTimezone(
    'Etc/GMT+11',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', -39600),
      '-11',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtPlus12 = FixedTimezone(
    'Etc/GMT+12',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', -43200),
      '-12',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtPlus2 = FixedTimezone(
    'Etc/GMT+2',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', -7200),
      '-02',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtPlus3 = FixedTimezone(
    'Etc/GMT+3',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', -10800),
      '-03',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtPlus4 = FixedTimezone(
    'Etc/GMT+4',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', -14400),
      '-04',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtPlus5 = FixedTimezone(
    'Etc/GMT+5',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', -18000),
      '-05',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtPlus6 = FixedTimezone(
    'Etc/GMT+6',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', -21600),
      '-06',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtPlus7 = FixedTimezone(
    'Etc/GMT+7',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', -25200),
      '-07',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtPlus8 = FixedTimezone(
    'Etc/GMT+8',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', -28800),
      '-08',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtPlus9 = FixedTimezone(
    'Etc/GMT+9',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', -32400),
      '-09',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus0 = FixedTimezone(
    'Etc/GMT-0',
    FixedTimezoneSpan(
      const LiteralOffset('Z', 0),
      'GMT',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus1 = FixedTimezone(
    'Etc/GMT-1',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', 3600),
      '+01',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus10 = FixedTimezone(
    'Etc/GMT-10',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', 36000),
      '+10',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus11 = FixedTimezone(
    'Etc/GMT-11',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', 39600),
      '+11',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus12 = FixedTimezone(
    'Etc/GMT-12',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', 43200),
      '+12',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus13 = FixedTimezone(
    'Etc/GMT-13',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', 46800),
      '+13',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus14 = FixedTimezone(
    'Etc/GMT-14',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', 50400),
      '+14',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus2 = FixedTimezone(
    'Etc/GMT-2',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', 7200),
      '+02',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus3 = FixedTimezone(
    'Etc/GMT-3',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', 10800),
      '+03',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus4 = FixedTimezone(
    'Etc/GMT-4',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', 14400),
      '+04',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus5 = FixedTimezone(
    'Etc/GMT-5',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', 18000),
      '+05',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus6 = FixedTimezone(
    'Etc/GMT-6',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', 21600),
      '+06',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus7 = FixedTimezone(
    'Etc/GMT-7',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', 25200),
      '+07',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus8 = FixedTimezone(
    'Etc/GMT-8',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', 28800),
      '+08',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmtMinus9 = FixedTimezone(
    'Etc/GMT-9',
    FixedTimezoneSpan(
      const LiteralOffset('+00:00', 32400),
      '+09',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone gmt0 = FixedTimezone(
    'Etc/GMT0',
    FixedTimezoneSpan(
      const LiteralOffset('Z', 0),
      'GMT',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone greenwich = FixedTimezone(
    'Etc/Greenwich',
    FixedTimezoneSpan(
      const LiteralOffset('Z', 0),
      'GMT',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone uct = FixedTimezone(
    'Etc/UCT',
    FixedTimezoneSpan(
      const LiteralOffset('Z', 0),
      'UTC',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone utc = FixedTimezone(
    'Etc/UTC',
    FixedTimezoneSpan(
      const LiteralOffset('Z', 0),
      'UTC',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone universal = FixedTimezone(
    'Etc/Universal',
    FixedTimezoneSpan(
      const LiteralOffset('Z', 0),
      'UTC',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

  static final Timezone zulu = FixedTimezone(
    'Etc/Zulu',
    FixedTimezoneSpan(
      const LiteralOffset('Z', 0),
      'UTC',
      TimezoneSpan.range.min,
      TimezoneSpan.range.max,
      dst: false,
    ),
  );

}


