// GENERATED CODE - DO NOT MODIFY BY HAND
//
// **************************************************************************
// Generated by: sugar/tool/timezone/main.dart
// **************************************************************************
// 
// ignore_for_file: type=lint

import 'package:sugar/src/time/offset.dart';
import 'package:sugar/src/time/zone/iana_timezones.dart';
import 'package:sugar/src/time/zone/timezone.dart';

extension Etc on Never {
  static final Timezone gmt = FixedTimezone('Etc/GMT', const RawOffset('Z', 0));

  static final Timezone gmtPlus0 = FixedTimezone('Etc/GMT+0', const RawOffset('Z', 0));

  static final Timezone gmtPlus1 = FixedTimezone('Etc/GMT+1', const RawOffset('-01:00', -3600));

  static final Timezone gmtPlus10 = FixedTimezone('Etc/GMT+10', const RawOffset('-10:00', -36000));

  static final Timezone gmtPlus11 = FixedTimezone('Etc/GMT+11', const RawOffset('-11:00', -39600));

  static final Timezone gmtPlus12 = FixedTimezone('Etc/GMT+12', const RawOffset('-12:00', -43200));

  static final Timezone gmtPlus2 = FixedTimezone('Etc/GMT+2', const RawOffset('-02:00', -7200));

  static final Timezone gmtPlus3 = FixedTimezone('Etc/GMT+3', const RawOffset('-03:00', -10800));

  static final Timezone gmtPlus4 = FixedTimezone('Etc/GMT+4', const RawOffset('-04:00', -14400));

  static final Timezone gmtPlus5 = FixedTimezone('Etc/GMT+5', const RawOffset('-05:00', -18000));

  static final Timezone gmtPlus6 = FixedTimezone('Etc/GMT+6', const RawOffset('-06:00', -21600));

  static final Timezone gmtPlus7 = FixedTimezone('Etc/GMT+7', const RawOffset('-07:00', -25200));

  static final Timezone gmtPlus8 = FixedTimezone('Etc/GMT+8', const RawOffset('-08:00', -28800));

  static final Timezone gmtPlus9 = FixedTimezone('Etc/GMT+9', const RawOffset('-09:00', -32400));

  static final Timezone gmtMinus0 = FixedTimezone('Etc/GMT-0', const RawOffset('Z', 0));

  static final Timezone gmtMinus1 = FixedTimezone('Etc/GMT-1', const RawOffset('+01:00', 3600));

  static final Timezone gmtMinus10 = FixedTimezone('Etc/GMT-10', const RawOffset('+10:00', 36000));

  static final Timezone gmtMinus11 = FixedTimezone('Etc/GMT-11', const RawOffset('+11:00', 39600));

  static final Timezone gmtMinus12 = FixedTimezone('Etc/GMT-12', const RawOffset('+12:00', 43200));

  static final Timezone gmtMinus13 = FixedTimezone('Etc/GMT-13', const RawOffset('+13:00', 46800));

  static final Timezone gmtMinus14 = FixedTimezone('Etc/GMT-14', const RawOffset('+14:00', 50400));

  static final Timezone gmtMinus2 = FixedTimezone('Etc/GMT-2', const RawOffset('+02:00', 7200));

  static final Timezone gmtMinus3 = FixedTimezone('Etc/GMT-3', const RawOffset('+03:00', 10800));

  static final Timezone gmtMinus4 = FixedTimezone('Etc/GMT-4', const RawOffset('+04:00', 14400));

  static final Timezone gmtMinus5 = FixedTimezone('Etc/GMT-5', const RawOffset('+05:00', 18000));

  static final Timezone gmtMinus6 = FixedTimezone('Etc/GMT-6', const RawOffset('+06:00', 21600));

  static final Timezone gmtMinus7 = FixedTimezone('Etc/GMT-7', const RawOffset('+07:00', 25200));

  static final Timezone gmtMinus8 = FixedTimezone('Etc/GMT-8', const RawOffset('+08:00', 28800));

  static final Timezone gmtMinus9 = FixedTimezone('Etc/GMT-9', const RawOffset('+09:00', 32400));

  static final Timezone gmt0 = FixedTimezone('Etc/GMT0', const RawOffset('Z', 0));

  static final Timezone greenwich = FixedTimezone('Etc/Greenwich', const RawOffset('Z', 0));

  static final Timezone uct = FixedTimezone('Etc/UCT', const RawOffset('Z', 0));

  static final Timezone utc = FixedTimezone('Etc/UTC', const RawOffset('Z', 0));

  static final Timezone universal = FixedTimezone('Etc/Universal', const RawOffset('Z', 0));

  static final Timezone zulu = FixedTimezone('Etc/Zulu', const RawOffset('Z', 0));

}


