// GENERATED CODE - DO NOT MODIFY BY HAND
//
// **************************************************************************
// Generated by: sugar/tool/timezone/main.dart
// **************************************************************************
// 
// ignore_for_file: type=lint

import 'dart:typed_data';

import 'package:sugar/src/time/offset.dart';
import 'package:sugar/src/time/zone/dynamic_timezone_rules.dart';
import 'package:sugar/src/time/zone/fixed_timezone_rules.dart';
import 'package:sugar/src/time/zone/timezone_rules.dart';

extension Indian on Never {
  static final TimezoneRules antananarivo = DynamicTimezoneRules(
    'Indian/Antananarivo',
    DynamicTimezone(
      -1,
      8836000,
      'Indian/Antananarivo',
      'LMT',
      null,
      -1946168836,
      dst: false,
    ),
    Int64List.fromList([ -1946168836000, -1309746600000, -1261969200000, -1041388200000, -865305900000 ]),
    Int32List.fromList([ 9000000, 10800000, 9000000, 9900000, 10800000 ]),
    [ '+0230', 'EAT', '+0230', '+0245', 'EAT' ],
    [ false, false, false, false, false ],
  );

  static final TimezoneRules chagos = DynamicTimezoneRules(
    'Indian/Chagos',
    DynamicTimezone(
      -1,
      17380000,
      'Indian/Chagos',
      'LMT',
      null,
      -1988167780,
      dst: false,
    ),
    Int64List.fromList([ -1988167780000, 820436400000 ]),
    Int32List.fromList([ 18000000, 21600000 ]),
    [ '+05', '+06' ],
    [ false, false ],
  );

  static final TimezoneRules christmas = DynamicTimezoneRules(
    'Indian/Christmas',
    DynamicTimezone(
      -1,
      24124000,
      'Indian/Christmas',
      'LMT',
      null,
      -2840164924,
      dst: false,
    ),
    Int64List.fromList([ -2840164924000, -1570084924000 ]),
    Int32List.fromList([ 24124000, 25200000 ]),
    [ 'BMT', '+07' ],
    [ false, false ],
  );

  static final TimezoneRules cocos = DynamicTimezoneRules(
    'Indian/Cocos',
    DynamicTimezone(
      -1,
      23087000,
      'Indian/Cocos',
      'LMT',
      null,
      -2840163887,
      dst: false,
    ),
    Int64List.fromList([ -2840163887000, -1577946287000, -873268200000, -778410000000 ]),
    Int32List.fromList([ 23087000, 23400000, 32400000, 23400000 ]),
    [ 'RMT', '+0630', '+09', '+0630' ],
    [ false, false, false, false ],
  );

  static final TimezoneRules comoro = DynamicTimezoneRules(
    'Indian/Comoro',
    DynamicTimezone(
      -1,
      8836000,
      'Indian/Comoro',
      'LMT',
      null,
      -1946168836,
      dst: false,
    ),
    Int64List.fromList([ -1946168836000, -1309746600000, -1261969200000, -1041388200000, -865305900000 ]),
    Int32List.fromList([ 9000000, 10800000, 9000000, 9900000, 10800000 ]),
    [ '+0230', 'EAT', '+0230', '+0245', 'EAT' ],
    [ false, false, false, false, false ],
  );

  static final TimezoneRules kerguelen = DynamicTimezoneRules(
    'Indian/Kerguelen',
    DynamicTimezone(
      -1,
      17640000,
      'Indian/Kerguelen',
      'LMT',
      null,
      -2840158440,
      dst: false,
    ),
    Int64List.fromList([ -2840158440000, -315636840000 ]),
    Int32List.fromList([ 17640000, 18000000 ]),
    [ 'MMT', '+05' ],
    [ false, false ],
  );

  static final TimezoneRules mahe = DynamicTimezoneRules(
    'Indian/Mahe',
    DynamicTimezone(
      -1,
      13272000,
      'Indian/Mahe',
      'LMT',
      null,
      -1577936472,
      dst: false,
    ),
    Int64List.fromList([ -1577936472000 ]),
    Int32List.fromList([ 14400000 ]),
    [ '+04' ],
    [ false ],
  );

  static final TimezoneRules maldives = DynamicTimezoneRules(
    'Indian/Maldives',
    DynamicTimezone(
      -1,
      17640000,
      'Indian/Maldives',
      'LMT',
      null,
      -2840158440,
      dst: false,
    ),
    Int64List.fromList([ -2840158440000, -315636840000 ]),
    Int32List.fromList([ 17640000, 18000000 ]),
    [ 'MMT', '+05' ],
    [ false, false ],
  );

  static final TimezoneRules mauritius = DynamicTimezoneRules(
    'Indian/Mauritius',
    DynamicTimezone(
      -1,
      13800000,
      'Indian/Mauritius',
      'LMT',
      null,
      -1988164200,
      dst: false,
    ),
    Int64List.fromList([ -1988164200000, 403041600000, 417034800000, 1224972000000, 1238274000000 ]),
    Int32List.fromList([ 14400000, 18000000, 14400000, 18000000, 14400000 ]),
    [ '+04', '+05', '+04', '+05', '+04' ],
    [ false, true, false, true, false ],
  );

  static final TimezoneRules mayotte = DynamicTimezoneRules(
    'Indian/Mayotte',
    DynamicTimezone(
      -1,
      8836000,
      'Indian/Mayotte',
      'LMT',
      null,
      -1946168836,
      dst: false,
    ),
    Int64List.fromList([ -1946168836000, -1309746600000, -1261969200000, -1041388200000, -865305900000 ]),
    Int32List.fromList([ 9000000, 10800000, 9000000, 9900000, 10800000 ]),
    [ '+0230', 'EAT', '+0230', '+0245', 'EAT' ],
    [ false, false, false, false, false ],
  );

  static final TimezoneRules reunion = DynamicTimezoneRules(
    'Indian/Reunion',
    DynamicTimezone(
      -1,
      13272000,
      'Indian/Reunion',
      'LMT',
      null,
      -1577936472,
      dst: false,
    ),
    Int64List.fromList([ -1577936472000 ]),
    Int32List.fromList([ 14400000 ]),
    [ '+04' ],
    [ false ],
  );

}


