// GENERATED CODE - DO NOT MODIFY BY HAND
//
// **************************************************************************
// Generated by: sugar/tool/timezone/main.dart
// **************************************************************************
// 
// ignore_for_file: type=lint

import 'package:sugar/src/time/offset.dart';
import 'package:sugar/src/time/zone/iana_timezones.dart';
import 'package:sugar/src/time/zone/timezone.dart';

extension Indian on Never {
  static final Timezone antananarivo = DynamicTimezone(
    'Indian/Antananarivo',
    const RawOffset('+02:27:16', 8836),
    [-1946168836, -1309746600, -1261969200, -1041388200, -865305900],
    const [
      RawOffset('+02:30', 9000),
      RawOffset('+03:00', 10800),
      RawOffset('+02:30', 9000),
      RawOffset('+02:45', 9900),
      RawOffset('+03:00', 10800),
    ],
  );

  static final Timezone chagos = DynamicTimezone(
    'Indian/Chagos',
    const RawOffset('+04:49:40', 17380),
    [-1988167780, 820436400],
    const [
      RawOffset('+05:00', 18000),
      RawOffset('+06:00', 21600),
    ],
  );

  static final Timezone christmas = DynamicTimezone(
    'Indian/Christmas',
    const RawOffset('+06:42:04', 24124),
    [-2840164924, -1570084924],
    const [
      RawOffset('+06:42:04', 24124),
      RawOffset('+07:00', 25200),
    ],
  );

  static final Timezone cocos = DynamicTimezone(
    'Indian/Cocos',
    const RawOffset('+06:24:47', 23087),
    [-2840163887, -1577946287, -873268200, -778410000],
    const [
      RawOffset('+06:24:47', 23087),
      RawOffset('+06:30', 23400),
      RawOffset('+09:00', 32400),
      RawOffset('+06:30', 23400),
    ],
  );

  static final Timezone comoro = DynamicTimezone(
    'Indian/Comoro',
    const RawOffset('+02:27:16', 8836),
    [-1946168836, -1309746600, -1261969200, -1041388200, -865305900],
    const [
      RawOffset('+02:30', 9000),
      RawOffset('+03:00', 10800),
      RawOffset('+02:30', 9000),
      RawOffset('+02:45', 9900),
      RawOffset('+03:00', 10800),
    ],
  );

  static final Timezone kerguelen = DynamicTimezone(
    'Indian/Kerguelen',
    const RawOffset('+04:54', 17640),
    [-2840158440, -315636840],
    const [
      RawOffset('+04:54', 17640),
      RawOffset('+05:00', 18000),
    ],
  );

  static final Timezone mahe = DynamicTimezone(
    'Indian/Mahe',
    const RawOffset('+03:41:12', 13272),
    [-1577936472],
    const [
      RawOffset('+04:00', 14400),
    ],
  );

  static final Timezone maldives = DynamicTimezone(
    'Indian/Maldives',
    const RawOffset('+04:54', 17640),
    [-2840158440, -315636840],
    const [
      RawOffset('+04:54', 17640),
      RawOffset('+05:00', 18000),
    ],
  );

  static final Timezone mauritius = DynamicTimezone(
    'Indian/Mauritius',
    const RawOffset('+03:50', 13800),
    [-1988164200, 403041600, 417034800, 1224972000, 1238274000],
    const [
      RawOffset('+04:00', 14400),
      RawOffset('+05:00', 18000),
      RawOffset('+04:00', 14400),
      RawOffset('+05:00', 18000),
      RawOffset('+04:00', 14400),
    ],
  );

  static final Timezone mayotte = DynamicTimezone(
    'Indian/Mayotte',
    const RawOffset('+02:27:16', 8836),
    [-1946168836, -1309746600, -1261969200, -1041388200, -865305900],
    const [
      RawOffset('+02:30', 9000),
      RawOffset('+03:00', 10800),
      RawOffset('+02:30', 9000),
      RawOffset('+02:45', 9900),
      RawOffset('+03:00', 10800),
    ],
  );

  static final Timezone reunion = DynamicTimezone(
    'Indian/Reunion',
    const RawOffset('+03:41:12', 13272),
    [-1577936472],
    const [
      RawOffset('+04:00', 14400),
    ],
  );

}


