name: Stevia Runner Unit Tests

on:
  push:
    paths:
      - .github/workflows/stevia_runner_unit_test.yaml
      - stevia_runner/example/**
      - stevia_runner/bin/**
      - stevia_runner/lib/**
      - stevia_runner/test/**
      - stevia_runner/tool/**
      - stevia_runner/analysis_options.yaml
      - stevia_runner/dartdoc_options.yaml
      - stevia_runner/pubspec.yaml

  pull_request:
    paths:
      - .github/workflows/stevia_runner_unit_test.yaml
      - stevia_runner/example/**
      - stevia_runner/bin/**
      - stevia_runner/lib/**
      - stevia_runner/test/**
      - stevia_runner/tool/**
      - stevia_runner/analysis_options.yaml
      - stevia_runner/dartdoc_options.yaml
      - stevia_runner/pubspec.yaml

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: stevia_runner

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.15.0
      - run: flutter pub get
      - run: flutter analyze
#      - run: flutter test
