name: Stevia

on:
  push:
    paths: [ stevia/**, .github/workflows/stevia.yaml ]

  pull_request:
    paths: [ stevia/**, .github/workflows/stevia.yaml ]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: stevia

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  android:
    name: Run Android integration tests
    runs-on: macos-latest
    defaults:
      run:
        working-directory: stevia/example
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: subosito/flutter-action@v2.10.0
      - run: flutter pub get
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          working-directory: stevia/example
          script: flutter test integration_test
      - run: flutter build appbundle --debug

  ios:
    name: Run iOS integration tests
    runs-on: macos-latest
    defaults:
      run:
        working-directory: stevia/example
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
      - uses: actions/checkout@v3
      - uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 14'
      - run: flutter pub get
      - run: flutter test integration_test
      - run: flutter build ios --debug --no-codesign
